import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { CreateShareDto } from './sharing.dto';
const details = {
  sourcePlan: { include: { edzes_napok: { orderBy: { sorrend: 'asc' as const }, include: { edzesterv_gyakorlatok: { orderBy: { sorrend: 'asc' as const }, include: { gyakorlatok: { select: { id: true, nev: true } } } } } } } },
  sender: { select: { id: true, username: true, nev: true, avatar_url: true } },
  recipient: { select: { id: true, username: true, nev: true, avatar_url: true } },
};
@Injectable()
export class SharingService {
  constructor(private readonly prisma: PrismaService) {}
  private async blocked(a: number, b: number) { return Boolean(await this.prisma.userBlock.findFirst({ where: { OR: [{ blockerId: a, blockedId: b }, { blockerId: b, blockedId: a }] } })); }
  async search(userId: number, query: string) { const normalized = query.trim().toLowerCase(); return this.prisma.userek.findMany({ where: { id: { not: userId }, profil_publikus: true, OR: [{ username_normalized: { contains: normalized, mode: 'insensitive' } }, { nev: { contains: query.trim(), mode: 'insensitive' } }] }, select: { id: true, username: true, nev: true, avatar_url: true }, take: 20 }); }
  async create(senderId: number, dto: CreateShareDto) { if (senderId === dto.recipientId) throw new ForbiddenException('Saját magadnak nem küldhetsz tervet.'); if (await this.blocked(senderId, dto.recipientId)) throw new ForbiddenException('Tiltott felhasználónak nem küldhetsz tervet.'); const plan = await this.prisma.edzestervek.findUnique({ where: { id: dto.planId } }); if (!plan || plan.user_id !== senderId) throw new ForbiddenException('Csak saját tervet küldhetsz.'); try { return await this.prisma.$transaction(async (tx) => { const share = await tx.planShare.create({ data: { sourcePlanId: dto.planId, senderId, recipientId: dto.recipientId, message: dto.message?.trim() || null, expiresAt: new Date(Date.now() + 14 * 86400000) }, include: details }); await tx.notification.create({ data: { recipientId: dto.recipientId, type: 'plan_share_received', resourceId: share.id } }); return share; }); } catch (e) { if ((e as { code?: string }).code === 'P2002') throw new ConflictException('Már van függő meghívó ehhez a tervhez.'); throw e; } }
  async list(userId: number, sent: boolean) { await this.expire(); return this.prisma.planShare.findMany({ where: sent ? { senderId: userId } : { recipientId: userId }, include: details, orderBy: { createdAt: 'desc' } }); }
  async accept(id: number, userId: number) { return this.prisma.$transaction(async (tx) => { const share = await tx.planShare.findUnique({ where: { id }, include: { sourcePlan: { include: { edzes_napok: { include: { edzesterv_gyakorlatok: true } } } } } }); if (!share || share.recipientId !== userId) throw new NotFoundException('A meghívó nem található.'); if (share.status === 'accepted' && share.copiedPlanId) return tx.edzestervek.findUniqueOrThrow({ where: { id: share.copiedPlanId } }); if (share.status !== 'pending' || share.expiresAt <= new Date()) throw new ConflictException('Ez a meghívó már nem fogadható el.'); const copy = await tx.edzestervek.create({ data: { user_id: userId, nev: `${share.sourcePlan.nev} (megosztva)`, leiras: share.sourcePlan.leiras, aktiv: true, publikus: false, edzes_napok: { create: share.sourcePlan.edzes_napok.map((d) => ({ nev: d.nev, sorrend: d.sorrend, edzesterv_gyakorlatok: { create: d.edzesterv_gyakorlatok.map((e) => ({ gyakorlat_id: e.gyakorlat_id, sorrend: e.sorrend, sorozatszam: e.sorozatszam, ismetlesszam_min: e.ismetlesszam_min, ismetlesszam_max: e.ismetlesszam_max, piheno_masodperc: e.piheno_masodperc, megjegyzese: e.megjegyzese })) } })) } } }); const updated = await tx.planShare.updateMany({ where: { id, status: 'pending', recipientId: userId }, data: { status: 'accepted', respondedAt: new Date(), copiedPlanId: copy.id } }); if (updated.count !== 1) throw new ConflictException('A meghívó állapota közben megváltozott.'); await tx.notification.create({ data: { recipientId: share.senderId, type: 'plan_share_accepted', resourceId: id } }); return copy; }); }
  async decline(id: number, userId: number) { const r = await this.prisma.planShare.updateMany({ where: { id, recipientId: userId, status: 'pending' }, data: { status: 'declined', respondedAt: new Date() } }); if (!r.count) throw new ConflictException('A meghívó már nem módosítható.'); return { success: true }; }
  async revoke(id: number, userId: number) { const r = await this.prisma.planShare.updateMany({ where: { id, senderId: userId, status: 'pending' }, data: { status: 'revoked', respondedAt: new Date() } }); if (!r.count) throw new ConflictException('A meghívó már nem vonható vissza.'); return { success: true }; }
  async expire() { await this.prisma.planShare.updateMany({ where: { status: 'pending', expiresAt: { lte: new Date() } }, data: { status: 'expired', respondedAt: new Date() } }); }
}
