import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import { AddExerciseDto, SetDto, StartWorkoutDto } from './workouts.dto';
const include = { exercises: { orderBy: { sorrend: 'asc' as const }, include: { sets: { orderBy: { sorrend: 'asc' as const } } } } };
@Injectable()
export class WorkoutsService {
  constructor(private readonly prisma: PrismaService) {}
  private async own(id: number, userId: number) { const session = await this.prisma.workoutSession.findUnique({ where: { id }, include }); if (!session) throw new NotFoundException('Az edzés nem található.'); if (session.userId !== userId) throw new ForbiddenException('Ez nem a saját edzésed.'); return session; }
  async start(userId: number, dto: StartWorkoutDto) {
    const active = await this.prisma.workoutSession.findFirst({ where: { userId, status: 'in_progress' } });
    if (active) throw new ForbiddenException('Egyszerre csak egy folyamatban lévő edzés lehet.');
    if (!dto.planDayId) return this.prisma.workoutSession.create({ data: { userId, note: dto.note?.trim() || null }, include });
    const day = await this.prisma.edzes_napok.findUnique({ where: { id: dto.planDayId }, include: { edzestervek: true, edzesterv_gyakorlatok: { orderBy: { sorrend: 'asc' }, include: { gyakorlatok: true } } } });
    if (!day || day.edzestervek.user_id !== userId) throw new ForbiddenException('Csak a saját tervnapodból indíthatsz edzést.');
    return this.prisma.workoutSession.create({ data: { userId, sourcePlanId: day.edzesterv_id, sourceDayId: day.id, note: dto.note?.trim() || null, exercises: { create: day.edzesterv_gyakorlatok.map((item) => ({ exerciseId: item.gyakorlat_id, exerciseName: item.gyakorlatok.nev, sorrend: item.sorrend, note: item.megjegyzese })) } }, include });
  }
  current(userId: number) { return this.prisma.workoutSession.findFirst({ where: { userId, status: 'in_progress' }, orderBy: { startedAt: 'desc' }, include }); }
  async addExercise(id: number, userId: number, dto: AddExerciseDto) { const session = await this.own(id, userId); if (session.status !== 'in_progress') throw new ForbiddenException('Lezárt edzés nem módosítható.'); const exercise = await this.prisma.gyakorlatok.findUnique({ where: { id: dto.exerciseId } }); if (!exercise) throw new NotFoundException('A gyakorlat nem található.'); return this.prisma.sessionExercise.create({ data: { sessionId: id, exerciseId: exercise.id, exerciseName: exercise.nev, sorrend: dto.sorrend ?? session.exercises.length + 1, note: dto.note?.trim() || null } }); }
  async addSet(id: number, exerciseId: number, userId: number, dto: SetDto) { const session = await this.own(id, userId); const exercise = session.exercises.find((x) => x.id === exerciseId); if (!exercise || session.status !== 'in_progress') throw new ForbiddenException('Nem módosítható sorozat.'); return this.prisma.workoutSet.create({ data: { sessionExerciseId: exerciseId, sorrend: exercise.sets.length + 1, repetitions: dto.repetitions, weight: dto.weight, rpe: dto.rpe, completed: dto.completed ?? false, completedAt: dto.completed ? new Date() : null } }); }
  async updateSet(id: number, setId: number, userId: number, dto: SetDto) { const session = await this.own(id, userId); const set = session.exercises.flatMap((x) => x.sets).find((x) => x.id === setId); if (!set || session.status !== 'in_progress') throw new ForbiddenException('Nem módosítható sorozat.'); return this.prisma.workoutSet.update({ where: { id: setId }, data: { repetitions: dto.repetitions, weight: dto.weight, rpe: dto.rpe, completed: dto.completed ?? false, completedAt: dto.completed ? new Date() : null } }); }
  async deleteSet(id: number, setId: number, userId: number) { const session = await this.own(id, userId); if (!session.exercises.some((x) => x.sets.some((set) => set.id === setId)) || session.status !== 'in_progress') throw new ForbiddenException('Nem módosítható sorozat.'); return this.prisma.workoutSet.delete({ where: { id: setId } }); }
  async finish(id: number, userId: number, cancelled = false) { const session = await this.own(id, userId); if (session.status !== 'in_progress') throw new ForbiddenException('Az edzés már lezárult.'); return this.prisma.workoutSession.update({ where: { id }, data: { status: cancelled ? 'cancelled' : 'completed', finishedAt: new Date() }, include }); }
  async history(userId: number, page: number, limit: number) { const where = { userId, status: { not: 'in_progress' as const } }; const [items, total] = await this.prisma.$transaction([this.prisma.workoutSession.findMany({ where, include, orderBy: { startedAt: 'desc' }, skip: (page - 1) * limit, take: limit }), this.prisma.workoutSession.count({ where })]); return { items, total, page, limit }; }
  async stats(userId: number) { const sessions = await this.prisma.workoutSession.findMany({ where: { userId, status: 'completed' }, include }); const sets = sessions.flatMap((s) => s.exercises.flatMap((e) => e.sets.map((set) => ({ ...set, name: e.exerciseName, startedAt: s.startedAt })))); const best = new Map<string, number>(); for (const set of sets) best.set(set.name, Math.max(best.get(set.name) ?? 0, Number(set.weight ?? 0) * set.repetitions)); return { workoutCount: sessions.length, totalVolume: sets.reduce((sum, set) => sum + Number(set.weight ?? 0) * set.repetitions, 0), bestByExercise: [...best].map(([exercise, volume]) => ({ exercise, volume })), activity: Object.entries(sessions.reduce<Record<string, number>>((a, s) => { const week = s.startedAt.toISOString().slice(0, 10); a[week] = (a[week] ?? 0) + 1; return a; }, {})).map(([date, count]) => ({ date, count })) }; }
}
